server:
  port: ${PORT}
spring:
  application:
    name: events
  kafka:
    topic: events
    bootstrap-servers: ${KAFKA_BROKERS}
    consumer:
      enable-auto-commit: true
      group-id: events-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.yandex.events.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
management:
  endpoints:
    web:
      base-path: /api/events
