apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: cinemaabyss-gateway
  namespace: cinemaabyss
spec:
  selector:
    istio: ingressgateway # стандартный Istio ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - cinemaabyss.example.com

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cinemaabyss-vs
  namespace: cinemaabyss
spec:
  hosts:
    - cinemaabyss.example.com
  gateways:
    - cinemaabyss-gateway
  http:
    - match:
        - uri:
            prefix: /api/movies
      route:
        - destination:
            host: movies-service
            port:
              number: 8081

    - match:
        - uri:
            prefix: /api/events
      route:
        - destination:
            host: events-service
            port:
              number: 8082

    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: monolith
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: movies-service-cb
  namespace: cinemaabyss
spec:
  host: movies-service.cinemaabyss.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 5
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 2
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50


---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: monolith-cb
  namespace: cinemaabyss
spec:
  host: monolith.cinemaabyss.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 20
        maxRequestsPerConnection: 5
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 20s
      maxEjectionPercent: 50