apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2doY3IuaW8iOiB7CgkJCSJhdXRocyI6ICJhMkZ1ZVdFek9EUTZaMmh3WDBST1IwUXhSME5rYWtwa2NUbDVhWE15Y2pWaVFsSTNaR00xTWtsa1J6SjBlRVp0WXdvPSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQo=
type: kubernetes.io/dockerconfigjson
